version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/projects/nipo
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ubuntu/projects/nipo
    owner: ubuntu
    group: www-data
    mode: 774
hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: www-data
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root