name: Nipo

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

   # Postgres service container
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:12.6
        # Provide the password for postgres
        env:
          POSTGRES_USER: psql_username
          POSTGRES_PASSWORD: psql_password
          POSTGRES_DB: nipo
          POSTGRES_HOST_AUTH_METHOD: trust
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        #Map container port to runner/host port 
        ports: 
          - 5432:5432


    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      # - name: Setup environment and databases
      #   run: |
      #     cat .github/workflows/gh_actions_env.txt >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          cat .github/workflows/gh_actions_env.txt >> $GITHUB_ENV
          python -m pip install --upgrade pip
          pip install pytest wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          psql -h localhost -d nipo -U psql_username -c 'SELECT 1;'
          pip install --use-feature=in-tree-build .
        # env:
          # The hostname used to communicate with the PostgreSQL service container
          # POSTGRES_USER: postgres
          # POSTGRES_HOST: localhost
          # # The default PostgreSQL port
          # POSTGRES_PORT: 5432
          # POSTGRES_PASS: psql_password
      - name: Test with pytest
        run: |
          cd nipo
          pytest

# Need to connect to psql db. 
# See https://docs.github.com/en/actions/guides/creating-postgresql-service-containers